version: 2.1

jobs:
  build:
    docker:
      - image: '********** CHANGE ME 1 **********'
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: '********** CHANGE ME 2 **********'
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud




# version: 2.1
# commands: # a reusable command with parameters
#   greeting:
#     parameters:
#       to:
#         default: "world"
#         type: string
#     steps:
#       - run: echo "Hello <<parameters.to>>"
# jobs:
#   my-job:
#     docker:
#       - image: cimg/base:stable
#     steps:
#       - greeting:
#           to: "My-Name"
# workflows:
#   my-workflow:
#     jobs:
#       - my-job




# # Couldn't automatically generate a config from your source code.
# # This is a generic template to serve as a base for your custom config
# # See: https://circleci.com/docs/configuration-reference
# # Stacks detected: cicd:empty:
# version: 2.1
# jobs:
#   test:
#     docker:
#       - image: cimg/base:stable
#     steps:
#       - checkout
#       # Replace this with a real test runner invocation
#       - run:
#           name: Run tests
#           command: echo 'replace me with real tests!' && false
#   build:
#     docker:
#       - image: cimg/base:stable
#     steps:
#       - checkout
#       # Replace this with steps to build a package, or executable
#       - run:
#           name: Build an artifact
#           command: touch example.txt
#       - store_artifacts:
#           path: example.txt
#   deploy:
#     docker:
#       - image: cimg/base:stable
#     steps:
#       # Replace this with steps to deploy to users
#       - run:
#           name: deploy
#           command: '#e.g. ./deploy.sh'
#       - run:
#           name: found empty repo
#           command: ':'
# workflows:
#   example:
#     jobs:
#       - test
#       - build:
#           requires:
#             - test
#       - deploy:
#           requires:
#             - test
